spring.application.name=devops-compose

# src/main/resources/application-local.properties
spring.datasource.url=jdbc:mysql://localhost:3306/devops_db
spring.datasource.username=root
spring.datasource.password=rootpassword
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

